### ISSUE TITLE
"Redux"-like not working

### ISSUE THREAD

**Issue by arvigeus** [IniZio/reim#27]
**Describe the bug**
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**To Reproduce**
1. Copy paste example code from https://github.com/IniZio/reim#redux-like
2. Run (tested with CRA 1.14)

**Expected behavior**
A component

**Additional context**
...

**Comment by IniZio** [comment]
Many thanks for your contribution, looking into it :thinking:

**Comment by IniZio** [comment]
The issue should be fixed with react-reim@1.10.3

Thanks for the reporting :)
