### ISSUE TITLE
What is the suggested way to use with ssr?

### ISSUE THREAD

**Issue by lishine** [IniZio/reim#37]
Next.js

**Comment by lishine** [comment]
OK, I will answer to myself :)
It works transparently with next-redux-wrapper
But instead of passing store through redux
```
                <Provider store={store}>
                    <Component {...pageProps} />
                </Provider>
```
I export the global store, here are the relevant snippets:
In _app:
```
export let globalStore

const makeStore = (initialState, options) => {
	return reim(initialState || { count: 8 })
}

	render() {
		if (process.browser) {
			console.log('in render')
			console.log('Router.pathname', Router.pathname)
		}
		const { Component, pageProps, store } = this.props
		console.log('store', store)
		globalStore = store
		return (
			<Container>
				<Component {...pageProps} />
			</Container>
		)
	}
```
In the component:
```
import React from 'react'
import Router from 'next/router'
import reim from 'reim'
import { useReim } from 'react-reim'
import Login from 'features/login/view/Login'
import { globalStore } from './_app'

const SignIn = (props, c) => {
	const [state, setState] = useReim(globalStore, state => state)
	const increment = () =>
		setState(s => {
			s.count++
		})

	return (
		<div>
			<button type="button" onClick={() => Router.push('/')}>
				home
			</button>
			<button onClick={increment}>+</button>
			<div id="count">{state.count}</div>
		</div>
	)

	// return <div>{/* <Login /> */}</div>
}
```

**Comment by IniZio** [comment]
Thanks for the issue! Since I do not often use Reim with SSR there is no official plugin for it yet. The way you suggested should work fine.

I may create a plugin for that in future :)

**Comment by lishine** [comment]
Thanks.
Questions.
1. Comparing use of hooks to easy-peasy, this lib uses useReim(store, getter) and the easy-peasy uses useStore(getter). So this lib is constructed in  a way to enable multiple stores, right ?
2. BTW, what is a getter not clear from the documentation. (on the hooks page)
3. In easy-peasy  there is  a case of parametrized hook, how reim handles that.
https://github.com/ctrlplusb/easy-peasy#consuming-state-in-your-components
4. Are selectors memoization on the roadmap ?
Of course it is easy to just wrap functions, I have used very nice lib
https://github.com/theKashey/memoize-state

**Comment by IniZio** [comment]
1. Yes in fact it is recommended to use reim in all kinds of cases from individual UI states using `<State/>` to Root-level state using `connect`
2. getter is a function that given a state returns what values you need, like
```js
state => ({
  count: state.count
})
```
I will update the documentation :P

**Comment by IniZio** [comment]
3. Has been done in #39, will be merged soon :)

**Comment by IniZio** [comment]
[react-reim@1.15.0](npm.im/react-reim) now supports parameterized hook

```js
const Product = ({ id }) => {
  const [state] = useReim(store, s => s.products[id], [id])
  return (
    <div>
      <h1>{product.title}</h1>
      <p>{product.description}</p>
    </div>
  );
};
```

**Comment by lishine** [comment]
What I understood about SSR is that it favors one global state

**Comment by IniZio** [comment]
@lishine That is because the state is stringified and assigned to `window.REDUX_STATE_OR_WTEVER` and then parse it in client.

For multiple stores like reim, you can make a unique name for each store then assign to `window.REIM_STORES[name]` so it should not be a problem :thinking:

**Comment by IniZio** [comment]
Done
